default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:
  host: db

development:
  <<: *default
  database: dummydb_development

test:
  <<: *default
  database: dummydb_test

production:
  <<: *default
  database: dummydb_production
  username: dummydb
  password: <%= ENV['DUMMYDB_DATABASE_PASSWORD'] %>
