default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: <%= ENV['POSTGRESQL_ENV_POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRESQL_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['POSTGRESQL_PORT_5432_TCP_PORT'] %>

development:
  <<: *default
  database: dummydb_development

test:
  <<: *default
  database: dummydb_test

production:
  <<: *default
  database: dummydb_production
  username: dummydb
  password: <%= ENV['DUMMYDB_DATABASE_PASSWORD'] %>
